name: Push to Release Branch 

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Branch to push to'
        required: true

env:
  ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

jobs:
  push-release-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
    - name: Fetch all branches
      run: git fetch --all

    - name: Check if branch exists
      id: check_branch
      run: |
        if git show-ref --verify --quiet refs/heads/${{ github.event.inputs.release_branch }}; then
          echo "branch_exists=true" >> $GITHUB_ENV
        else
          echo "branch_exists=false" >> $GITHUB_ENV
        fi
    - name: Create or checkout branch
      run: |
        if [ "$branch_exists" = "true" ]; then
          git checkout ${{ github.event.inputs.release_branch }}
        else
          git checkout -b ${{ github.event.inputs.release_branch }}
        fi
    - name: Push to release branch  
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
        git push origin ${{ github.event.inputs.release_branch }}
